# Generated by Django 5.2.6 on 2025-09-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('mana_cost', models.IntegerField()),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='Magic.ability')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('faction', models.CharField(blank=True, max_length=100)),
                ('abilities', models.ManyToManyField(blank=True, to='Magic.ability')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='basic', max_length=20)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magic.hero')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magic.skill')),
            ],
            options={
                'unique_together': {('hero', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(through='Magic.HeroSkill', to='Magic.skill'),
        ),
        migrations.AddField(
            model_name='hero',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Magic.specialization'),
        ),
    ]
