# Generated by Django 5.2.5 on 2025-09-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('faction', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('hero', 'Hero')], default='basic', max_length=20)),
                ('content', models.TextField()),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='Magic.ability')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Magic.skill')),
            ],
        ),
        migrations.CreateModel(
            name='HeroAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_links', to='Magic.ability')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_abilities', to='Magic.hero')),
            ],
            options={
                'unique_together': {('hero', 'ability')},
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='heroes', through='Magic.HeroAbility', through_fields=('hero', 'ability'), to='Magic.ability'),
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(to='Magic.skill'),
        ),
        migrations.AddField(
            model_name='hero',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Magic.specialization'),
        ),
    ]
