# Generated by Django 5.2.6 on 2025-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='mana_cost',
        ),
        migrations.AlterField(
            model_name='ability',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
