# Generated by Django 5.2.5 on 2025-09-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0002_rename_description_skill_content_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='heroability',
            unique_together={('hero', 'ability')},
        ),
        migrations.AddField(
            model_name='ability',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('hero', 'Hero')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='ability',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Magic.skill'),
        ),
        migrations.AddField(
            model_name='heroability',
            name='ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aility_links', to='Magic.ability'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='abilities',
            field=models.ManyToManyField(blank=True, null=True, related_name='heroes', through='Magic.HeroAbility', through_fields=('hero', 'ability'), to='Magic.ability'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(to='Magic.skill'),
        ),
        migrations.AlterField(
            model_name='heroability',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_abilities', to='Magic.hero'),
        ),
        migrations.RemoveField(
            model_name='heroability',
            name='level',
        ),
        migrations.RemoveField(
            model_name='heroability',
            name='skill',
        ),
    ]
